# Generated by Django 5.0.6 on 2024-06-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(max_length=20)),
                ('class_name', models.CharField(max_length=20)),
                ('year_of_employment', models.PositiveSmallIntegerField()),
                ('subject', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('hobby', models.CharField(max_length=20)),
            ],
        ),
    ]
