# Generated by Django 5.0.7 on 2024-07-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='hobby',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='teacher',
            name='id_number',
            field=models.PositiveSmallIntegerField(default=12345),
        ),
        migrations.AddField(
            model_name='teacher',
            name='mode_of_payment',
            field=models.CharField(default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='class_name',
            field=models.CharField(default='Class A', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='country',
            field=models.CharField(default='USA', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='john.doe@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default='John', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default='Doe', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(default='Mathematics', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='year_of_employment',
            field=models.PositiveSmallIntegerField(default=2024),
        ),
    ]
