# Generated by Django 5.0.6 on 2024-06-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_course', models.CharField(max_length=20)),
                ('number_of_units', models.IntegerField()),
                ('number_of_students', models.IntegerField()),
                ('course_code', models.IntegerField()),
                ('qualification', models.CharField(max_length=20)),
                ('registration_characteristic', models.CharField(max_length=20)),
                ('number_of_trainers', models.IntegerField()),
                ('scheduled_time', models.TimeField()),
                ('course_requirements', models.CharField(max_length=20)),
                ('year_introduced', models.IntegerField()),
            ],
        ),
    ]
