# Generated by Django 5.0.7 on 2024-07-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_class', models.CharField(default='', max_length=255)),
                ('number_of_students', models.IntegerField()),
                ('number_of_tables', models.IntegerField()),
                ('number_of_chairs', models.IntegerField(default=0)),
                ('number_of_boards', models.IntegerField()),
                ('class_trainer', models.CharField(max_length=20)),
                ('class_prefect', models.CharField(max_length=20)),
                ('number_of_laptops', models.IntegerField()),
                ('number_of_televisions', models.IntegerField()),
                ('number_of_windows', models.IntegerField()),
            ],
        ),
    ]
