# Generated by Django 5.0.6 on 2024-06-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_class', models.CharField(max_length=20)),
                ('number_of_students', models.IntegerField()),
                ('number_of_tables', models.IntegerField()),
                ('class_size', models.IntegerField()),
                ('class_equipment', models.CharField(max_length=20)),
                ('class_trainer', models.CharField(max_length=20)),
                ('color_of_chairs', models.CharField(max_length=20)),
                ('number_of_laptops', models.IntegerField()),
                ('number_of_televisions', models.IntegerField()),
                ('number_of_windows', models.IntegerField()),
            ],
        ),
    ]
